### ISSUE TITLE
Development plan/roadmap

### ISSUE THREAD

**Issue by ninogogol** [ninogogol/equalizer-landing-page#1]
- [ ] Implament header component
- [ ] Implament main text component
- [ ] Implament Illustration component with background and foreground with downloads section
- [ ] Implament footer and Social Icons
- [ ] configure on github
